version: "3.8"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql/db_structure.sql:/docker-entrypoint-initdb.d/db_structure.sql
    restart: always
  app:
    tty: true
    build:
      context: "./app"
      dockerfile: Dockerfile
    container_name: app-container
    command: >
      bash -c "python /app/scripts/ingestion.py && python /app/scripts/app.py"
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - db